services:
  todoapp-postgres:
    image: postgres:18.6-bookworm
    container_name: todoapp-env-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always

  todoapp-postgres-migrate:
    image: migrate/migrate:v4.20.1
    volumes:
      - ${PROJECT_ROOT}/out/migrations:/migrations
